import { ArrowLeft } from "lucide-react";

interface TermsAndConditionsPageProps {
  onBack: () => void;
}

export function TermsAndConditionsPage({ onBack }: TermsAndConditionsPageProps) {
  return (
    <div className="min-h-screen bg-surface-50 flex flex-col">
      {/* Header */}
      <header className="h-16 px-4 sm:px-6 lg:px-8 border-b border-slate-200 bg-white flex items-center justify-between shrink-0 sticky top-0 z-10">
        <button 
          onClick={onBack}
          className="flex items-center gap-2.5 hover:opacity-80 transition-opacity text-left cursor-pointer"
          aria-label="Return to homepage"
        >
          <img src="/LucaLogo.png" alt="LUCA" className="h-7 w-auto object-contain" />
          <span className="text-slate-900 text-[15px] font-bold tracking-[0.18em]">LUCA</span>
        </button>
        <button 
          onClick={onBack}
          className="text-sm font-medium text-slate-500 hover:text-slate-900 transition-colors inline-flex items-center gap-1.5 cursor-pointer"
        >
          <ArrowLeft size={16} />
          Back to site
        </button>
      </header>

      {/* Content */}
      <main className="flex-1 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-[var(--shadow-card)] border border-slate-200 p-8 md:p-12">
          
          <div className="mb-10 border-b border-slate-200 pb-8">
            <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4">Terms & Conditions</h1>
            <p className="text-slate-500 font-medium">Updated at July 6, 2026</p>
          </div>

          <div className="prose prose-slate max-w-none prose-headings:font-bold prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4 prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-3 prose-p:text-slate-600 prose-p:leading-relaxed prose-li:text-slate-600">
            
            <h2>General Terms</h2>
            <p>
              By accessing and placing an order with LUCA, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and RHOMU LTD. Under no circumstances shall the RHOMU LTD team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if the RHOMU LTD team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof. RHOMU LTD will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
            </p>

            <h2>License</h2>
            <p>
              RHOMU LTD grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and RHOMU LTD (referred to in these Terms & Conditions as "RHOMU LTD", "us", "we" or "our"), the provider of the LUCA website and the services accessible from the LUCA website (which are collectively referred to in these Terms & Conditions as the "LUCA Service"). You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the LUCA Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
            </p>

            <h2>Definitions and key terms</h2>
            <p>To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when these terms mention "Company," "we," "us," or "our," it refers to RHOMU LTD, that is responsible for your information under these Terms & Conditions.</li>
              <li><strong>Country:</strong> where RHOMU LTD or the owners/founders of RHOMU LTD are based, in this case is Ireland.</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit LUCA and use the services.</li>
              <li><strong>Service:</strong> refers to the service provided by LUCA as described in the relative terms (if available) and on this platform.</li>
              <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
              <li><strong>Website:</strong> LUCA's official site.</li>
              <li><strong>You:</strong> a person or entity that is registered with LUCA to use the Services.</li>
            </ul>

            <h2>Restrictions</h2>
            <p>You agree not to, and you will not permit others to:</p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
              <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of RHOMU LTD or its affiliates, partners, suppliers or the licensors of the website.</li>
            </ul>

            <h2>Return and Refund Policy</h2>
            <p>
              Thanks for shopping at LUCA. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products. As with any shopping experience, there are terms and conditions that apply to transactions at LUCA. By placing an order or making a purchase at LUCA, you agree to the terms along with LUCA's Privacy Policy. If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us at contactus@rhomultd.com and we will discuss any of the issues you are going through with our product.
            </p>

            <h2>Your Suggestions</h2>
            <p>
              Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to RHOMU LTD with respect to the website shall remain the sole and exclusive property of RHOMU LTD. RHOMU LTD shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
            </p>

            <h2>Your Consent</h2>
            <p>
              We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
            </p>

            <h2>Links to Other Websites</h2>
            <p>
              This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by RHOMU LTD. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.
            </p>

            <h2>Cookies</h2>
            <p>
              RHOMU LTD uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>

            <h2>Changes To Our Terms & Conditions</h2>
            <p>
              You acknowledge and agree that RHOMU LTD may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at RHOMU LTD's sole discretion, without prior notice to you. You may stop using the Service at any time. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
            </p>

            <h2>Modifications & Updates to Our website</h2>
            <p>
              RHOMU LTD reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you. RHOMU LTD may from time to time provide enhancements or improvements to the features/functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").
            </p>

            <h2>Third-Party Services</h2>
            <p>
              We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services"). You acknowledge and agree that RHOMU LTD shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof.
            </p>

            <h2>Term and Termination</h2>
            <p>
              This Agreement shall remain in effect until terminated by you or RHOMU LTD. RHOMU LTD may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from RHOMU LTD, in the event that you fail to comply with any provision of this Agreement.
            </p>

            <h2>Copyright Infringement Notice</h2>
            <p>
              If you are a copyright owner or such owner's agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the required information including identification of the material, contact information, and a statement made under penalty of perjury.
            </p>

            <h2>Indemnification</h2>
            <p>
              You agree to indemnify and hold RHOMU LTD and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.
            </p>

            <h2>No Warranties & Limitation of Liability</h2>
            <p>
              The website is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted by applicable law, in no event shall RHOMU LTD or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to damages for loss of profits, for loss of data or other information, for business interruption, for personal injury for loss of privacy arising out of or in any way related to the use of or inability to use the website).
            </p>

            <h2>Severability & Waiver</h2>
            <p>
              If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect. Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter.
            </p>

            <h2>Intellectual Property</h2>
            <p>
              The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by RHOMU LTD, its licensors or other providers of such material and are protected by Ireland and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.
            </p>

            <h2>Agreement to Arbitrate & Notice of Dispute</h2>
            <p>
              This section applies to any dispute EXCEPT IT DOESN'T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR RHOMU LTD's INTELLECTUAL PROPERTY RIGHTS. In the event of a dispute, you or RHOMU LTD must give the other a Notice of Dispute. You must send any Notice of Dispute via email to: contactus@rhomultd.com.
            </p>

            <h2>Miscellaneous</h2>
            <p>
              RHOMU LTD operates and controls the LUCA Service from its offices in Ireland. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. These Terms & Conditions (which include and incorporate the LUCA Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and RHOMU LTD concerning its subject matter, and cannot be changed or modified by you.
            </p>

            <h2 className="mt-12">Contact Us</h2>
            <p>Don't hesitate to contact us if you have any questions.</p>
            <ul className="list-none pl-0 mt-4 font-medium text-slate-900">
              <li>Via Email: <a href="mailto:contactus@rhomultd.com" className="text-primary hover:underline">contactus@rhomultd.com</a></li>
            </ul>

          </div>
        </div>
      </main>
    </div>
  );
}